In [13]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data collection and Preprocessing

In [5]:
movies_data=pd.read_csv("/content/sample_data/movies.csv")


# New Section

In [6]:
movies_data.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [7]:
movies_data.shape

(4803, 24)

In [8]:
#Feature Selection 
features=['genres','keywords','cast','tagline','director','overview']

In [9]:
#removing null and replacing missing values
for feature in features:
   movies_data[feature]=movies_data[feature].fillna(' ')

In [11]:
new_feature=""
for x in features:
  new_feature+=movies_data[x]
new_feature

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy Romance Edward Burns Kerry Bish\u00e9 M...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801      Daniel Henney Eliza Coupe Bill Paxton Alan R...
4802    Documentaryobsession camcorder crush dream gir...
Name: genres, Length: 4803, dtype: object

In [14]:
#using vectorizer converting text data to vectors
vectorizer=TfidfVectorizer()

In [15]:
#making vectors
vectors=vectorizer.fit_transform(new_feature)

In [17]:
print(vectors)

  (0, 7143)	0.15826749134367513
  (0, 1417)	0.12021074245993765
  (0, 1722)	0.05229052986251473
  (0, 31038)	0.16289251056462536
  (0, 1760)	0.030371862815529095
  (0, 28624)	0.15439610381617702
  (0, 15351)	0.13788454200714487
  (0, 4046)	0.09510372532590984
  (0, 39667)	0.1403943504797269
  (0, 3663)	0.09320462062963875
  (0, 5618)	0.058893553713405634
  (0, 26267)	0.10516105942595694
  (0, 41032)	0.14724726780213568
  (0, 28494)	0.04713939203721723
  (0, 26554)	0.1463809487555932
  (0, 39537)	0.02951277243876469
  (0, 11072)	0.17622320126200586
  (0, 20686)	0.039648428225638445
  (0, 24849)	0.13848764126676258
  (0, 29171)	0.19273476307103798
  (0, 6482)	0.12078477381071452
  (0, 258)	0.18741922743424136
  (0, 5823)	0.19958768039344676
  (0, 20907)	0.0838213682083548
  (0, 29093)	0.3588081447473151
  :	:
  (4802, 40176)	0.08417805812314053
  (4802, 38839)	0.06819887608188853
  (4802, 28119)	0.06567211179665963
  (4802, 17620)	0.0836550595526221
  (4802, 42534)	0.08265455566000413
  

In [19]:
#Getting similarity Score for every movie and compare this score
#to show which movie is similar to which
similarity_score=cosine_similarity(vectors)
print(similarity_score)


[[1.         0.04604487 0.02112422 ... 0.02550583 0.01167995 0.00662635]
 [0.04604487 1.         0.03908278 ... 0.04584161 0.03161789 0.01600715]
 [0.02112422 0.03908278 1.         ... 0.02562645 0.0119831  0.0144874 ]
 ...
 [0.02550583 0.04584161 0.02562645 ... 1.         0.03832301 0.02017173]
 [0.01167995 0.03161789 0.0119831  ... 0.03832301 1.         0.0335062 ]
 [0.00662635 0.01600715 0.0144874  ... 0.02017173 0.0335062  1.        ]]


In [21]:
#comapre every movie with every other movie
similarity_score.shape

(4803, 4803)

In [53]:
# #input movie name from user
# movie_name=input("Enter ur movie name ")

Enter ur movie name matrix


In [54]:
# #creating list of movies from dataset just storing the title
# movie=movies_data['title'].tolist()
# print(movie)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [55]:
# similar_movies=difflib.get_close_matches(movie_name,movie)

# similar_movies

['The Matrix']

In [56]:
# close_matched=similar_movies[0]
# close_matched

'The Matrix'

In [57]:
# #find row index for closed_match movie
# #so that we can compare with its attributes
# idx=movies_data[movies_data.title==close_matched]['index'].values[0]
# idx

634

In [58]:
# #list of similar movies
# similarity_movie_score=list(enumerate(similarity_score[idx]))
# print(similarity_movie_score)
# #index,similarity_score_of_movie...eg:-0 means avatar with similar score as 0.035

[(0, 0.08853316169716428), (1, 0.05595824626230966), (2, 0.02184467527569019), (3, 0.04484849122602491), (4, 0.0541916832862689), (5, 0.021760505792258338), (6, 0.027686827280143808), (7, 0.056343779344106705), (8, 0.011223038268254241), (9, 0.024497755893251157), (10, 0.0700839025699226), (11, 0.033566035410012865), (12, 0.008438319901032434), (13, 0.030759390780681312), (14, 0.10038951581601595), (15, 0.0435730055424493), (16, 0.04427909160513557), (17, 0.050114244231791005), (18, 0.05696373331907663), (19, 0.07567644929243521), (20, 0.032329845672862796), (21, 0.034706243355181854), (22, 0.022444368758066213), (23, 0.022395136023527145), (24, 0.02900418532251278), (25, 0.04983598281671488), (26, 0.04638164935193288), (27, 0.05629088851483025), (28, 0.03029366262771593), (29, 0.056691394461259724), (30, 0.03369702126468694), (31, 0.03959208852042116), (32, 0.04806733698607192), (33, 0.03780967489555416), (34, 0.014370069706855754), (35, 0.02686833100833159), (36, 0.07778927807897944)

In [59]:
# movie_list=sorted(similarity_movie_score,key=lambda x:x[1],reverse=True)
#print(movie_list)

[(634, 1.0000000000000002), (123, 0.373085868991599), (125, 0.2718303099549676), (95, 0.17060652561608206), (3439, 0.14455169899594686), (93, 0.14411576714914126), (2966, 0.14383587184957827), (1281, 0.13269682367034374), (1296, 0.12162796314341649), (2752, 0.11652253427402456), (2160, 0.11451117542441687), (2088, 0.11154526623872073), (870, 0.11120707523293398), (333, 0.11010913939817149), (2996, 0.10698390432429787), (169, 0.10621418099928862), (2900, 0.10373026601247667), (301, 0.10336804087758883), (150, 0.10324159117012854), (266, 0.10207084340417505), (487, 0.1005931116343556), (2638, 0.10058210325625802), (127, 0.10054042408795191), (14, 0.10038951581601595), (1617, 0.10028265041811613), (889, 0.0991226938725159), (59, 0.09908345915087514), (2001, 0.09841257165411811), (2386, 0.09840800323248906), (116, 0.09745800676666966), (3410, 0.09655159055541286), (342, 0.09602025085190048), (3461, 0.09449997260232279), (2484, 0.09447939202582567), (3776, 0.09370969850442029), (1725, 0.093

In [60]:
# #print name of movies based on index
# print("Suggested Movies are : ")
# j=0
# for i in movie_list:
#   suggested_movie=movies_data[movies_data.index==i[0]]['title'].values[0]
#   print(suggested_movie)
#   j+=1
#   if(j==10):
#     break

Suggested Movies are : 
The Matrix
The Matrix Revolutions
The Matrix Reloaded
Interstellar
The Terminator
Terminator 3: Rise of the Machines
2001: A Space Odyssey
Hackers
Superman III
Ex Machina


In [62]:
#ALL in one Frame
#input movie name from user
movie_name=input("Enter ur movie name ")

#creating list of movies from dataset just storing the title
movie=movies_data['title'].tolist()

similar_movies=difflib.get_close_matches(movie_name,movie)

close_matched=similar_movies[0]
close_matched

#find row index for closed_match movie
#so that we can compare with its attributes
idx=movies_data[movies_data.title==close_matched]['index'].values[0]

#list of similar movies
similarity_movie_score=list(enumerate(similarity_score[idx]))

movie_list=sorted(similarity_movie_score,key=lambda x:x[1],reverse=True)

#print name of movies based on index
print("Suggested Movies are : ")
j=0
for i in movie_list:
  suggested_movie=movies_data[movies_data.index==i[0]]['title'].values[0]
  print(suggested_movie)
  j+=1
  if(j==25):
    break

Enter ur movie name spiderman
Suggested Movies are : 
Spider-Man
Spider-Man 3
Spider-Man 2
Arachnophobia
The Amazing Spider-Man 2
Charlotte's Web
The Amazing Spider-Man
Shadow of the Vampire
xXx: State of the Union
Speed 2: Cruise Control
Midnight Special
21 Jump Street
The Covenant
The Notebook
Gremlins 2: The New Batch
The Reef
Finding Nemo
Clear and Present Danger
Drag Me to Hell
Home for the Holidays
Brothers
The Virgin Suicides
Losin' It
Daybreakers
The Good German
